# Generated by Django 6.0.4 on 2026-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default='dingus', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
